### ISSUE TITLE
option to disable startup notifications

### ISSUE THREAD

**Issue by tuxpingu** [RyotaUshio/obsidian-math-in-callout#1]
Hello, thank you for making this plugin! 

Would you consider adding an option to disable the "You're not ready yet" notification displayed when Obsidian is launched (and the following "You're ready" one)? 

Thank you.

**Comment by RyotaUshio** [comment]
Released as [0.3.7](https://github.com/RyotaUshio/obsidian-math-in-callout/releases/tag/0.3.7).

**Comment by tuxpingu** [comment]
thank you!
